# Generated by Django 5.2.8 on 2025-11-17 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0002_room_maintenance_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostel_app.room'),
        ),
    ]
